export const GET_WORKS = 'GET_WORKS';
export const GET_WORKS_LOADED = 'GET_WORKS_LOADED';
export const GET_WORKS_LOADING = 'GET_WORKS_LOADING';

export const GET_WORK = 'GET_WORK';
export const GET_WORK_LOADED = 'GET_WORK_LOADED';
export const GET_WORK_LOADING = 'GET_WORK_LOADING';

export const SAVE_WORK = 'SAVE_WORK';

export const GET_CERTIFICATES = 'GET_CERTIFICATES';
export const GET_CERTIFICATES_LOADED = 'GET_CERTIFICATES_LOADED';
export const GET_CERTIFICATES_LOADING = 'GET_CERTIFICATES_LOADING';

export const GET_CERTIFICATE = 'GET_CERTIFICATE';
export const GET_CERTIFICATE_LOADED = 'GET_CERTIFICATE_LOADED';
export const GET_CERTIFICATE_LOADING = 'GET_CERTIFICATE_LOADING';

export const SAVE_CERTIFICATE = 'SAVE_CERTIFICATE';

export const GET_BLOGS = 'GET_BLOGS';
export const GET_BLOGS_LOADED = 'GET_BLOGS_LOADED';
export const GET_BLOGS_LOADING = 'GET_BLOGS_LOADING';

export const GET_BLOG = 'GET_BLOG';
export const GET_BLOG_LOADED = 'GET_BLOG_LOADED';
export const GET_BLOG_LOADING = 'GET_BLOG_LOADING';

export const SAVE_BLOG = 'SAVE_BLOG';